version: '3'
services:
  app:
    build: 
      context: .
      target: production
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED:-true}"
