version: '3'
services:
  app:
    image: ghcr.io/lexuzieel/cerebro-topic-router-bot:edge
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED:-true}"
